# DSA 504 — Homework 1
## Exploring Retail Sales with pandas

**Assigned:** Class 5 (Wednesday, Sep 16)
**Due:** Before Class 7 (Monday, Sep 23)
**Worth:** 1 of 6 homework assignments (homework is 50% of your final grade, split evenly across all 6)

---

### Instructions

- Use `retail_sales.csv` (the same dataset from Class 4–5) — make sure it's in the same folder as this notebook.
- Fill in each `# TODO` code cell below. Do not delete the cells or reorder them.
- A few cells ask a **short written question** — answer these in the markdown cell provided (just a sentence or two, not an essay).
- **Do not clean the data yet.** You will notice missing values and inconsistent category names (e.g., `"Electronics"` vs `"electronics"`) while working through this — that's expected. Cleaning is covered in Classes 6–7. For this assignment, just work with the data as-is.
- **AI use:** if you use an AI tool for help on any part of this assignment, briefly note where and how in the markdown cell at the very bottom of this notebook, per the course AI-use policy in the syllabus.


### Grading breakdown
| Section | Weight |
|---|---|
| Part 1 — Load & Inspect | 15% |
| Part 2 — Select & Filter | 25% |
| Part 3 — Sort | 20% |
| Part 4 — Group & Aggregate | 30% |
| Part 5 — Written Reflection | 10% |

In [3]:
import pandas as pd
import numpy as np

sales = pd.read_csv("retail_sales.csv")
sales.head()

         date     store     category  units_sold  revenue
0  2025-04-22      Rome         Toys        25.0   402.50
1  2025-04-12  Syracuse  electronics        38.0  3154.00
2  2025-12-21     Utica   home goods        42.0  1299.06
3  2025-02-11  Syracuse  Electronics        60.0  5114.40
4  2025-04-10  Syracuse         toys        10.0   147.10

---
## Part 1 — Load & Inspect (15%)

Recall the basic inspection tools from Class 4.

**1a.** Print the shape of the dataset, the column names, and the data type of each column.

In [6]:
# TODO 1a
# 1a: Print the dataset dimensions (rows, columns), column names, and data type of each column
print("Shape:", sales.shape)
print("\nColumns:", sales.columns)
print("\nData Types:\n", sales.dtypes)

Shape: (4039, 5)

Columns: Index(['date', 'store', 'category', 'units_sold', 'revenue'], dtype='str')

Data Types:
 date              str
store             str
category          str
units_sold    float64
revenue       float64
dtype: object

**1b.** Print how many missing values exist in each column.

In [7]:
# TODO 1b
# 1b: Count the number of missing (NaN) values in each column of the DataFrame
sales.isnull().sum()

date           0
store          0
category       0
units_sold    60
revenue       60
dtype: int64

**1c. Written question:** Looking at the unique values in the `category` column, how many *distinct text values* does pandas report, and how many *real* categories do you believe actually exist? Why the difference?

*Your answer here:*

In [8]:
# TODO 1c -- write the code that lets you answer the question above
# 1c: Count the frequency of each unique value in the 'category' column, including missing values
sales['category'].value_counts(dropna=False)

category
Groceries      438
toys           411
groceries      401
Toys           383
clothing       297
Electronics    276
Home_Goods     275
Home Goods     273
Cloth ing      267
home goods     266
electronics    265
Clothing       255
ELECTRONICS    232
Name: count, dtype: int64

---
## Part 2 — Select & Filter (25%)

**2a.** Select just the `store`, `category`, and `revenue` columns into a new variable. Print the first 5 rows of the result.

In [9]:
# TODO 2a
# 2a: Select a subset of specific columns ('store', 'category', 'revenue') into a new DataFrame
subset_df = sales[['store', 'category', 'revenue']]
subset_df.head()

      store     category  revenue
0      Rome         Toys   402.50
1  Syracuse  electronics  3154.00
2     Utica   home goods  1299.06
3  Syracuse  Electronics  5114.40
4  Syracuse         toys   147.10

**2b.** Filter the full dataset down to rows where `revenue` is greater than 3000. How many rows match?

In [10]:
# TODO 2b
# 2b: Filter rows using a single condition (e.g., revenue greater than 1000)
high_revenue = sales[sales['revenue'] > 1000]
high_revenue.head()

          date     store     category  units_sold  revenue
1   2025-04-12  Syracuse  electronics        38.0  3154.00
2   2025-12-21     Utica   home goods        42.0  1299.06
3   2025-02-11  Syracuse  Electronics        60.0  5114.40
5   2025-05-07     Utica  Electronics        39.0  3531.06
13  2025-03-09    Albany     Clothing        93.0  2309.19

**2c.** Filter the dataset to rows where the store is `"Albany"` **and** `units_sold` is greater than 100. How many rows match?

In [11]:
# TODO 2c
# 2c: Filter rows using two combined conditions (e.g., revenue > 1000 AND units_sold > 10)
filtered_sales = sales[(sales['revenue'] > 1000) & (sales['units_sold'] > 10)]
filtered_sales.head()

          date     store     category  units_sold  revenue
1   2025-04-12  Syracuse  electronics        38.0  3154.00
2   2025-12-21     Utica   home goods        42.0  1299.06
3   2025-02-11  Syracuse  Electronics        60.0  5114.40
5   2025-05-07     Utica  Electronics        39.0  3531.06
13  2025-03-09    Albany     Clothing        93.0  2309.19

**2d.** Using `.isin()`, filter the dataset down to only rows where the store is `"Utica"` or `"Rome"`.

In [12]:
# TODO 2d
# 2d: Filter rows using .isin() against a list of specific store names
target_stores = ['Syracuse', 'Utica']
store_sales = sales[sales['store'].isin(target_stores)]
store_sales.head()

         date     store     category  units_sold  revenue
1  2025-04-12  Syracuse  electronics        38.0  3154.00
2  2025-12-21     Utica   home goods        42.0  1299.06
3  2025-02-11  Syracuse  Electronics        60.0  5114.40
4  2025-04-10  Syracuse         toys        10.0   147.10
5  2025-05-07     Utica  Electronics        39.0  3531.06

---
## Part 3 — Sort (20%)

**3a.** Sort the full dataset by `revenue` in descending order, and print just the `date`, `store`, `category`, and `revenue` columns for the top 5 rows.

In [13]:
# TODO 3a
# 3a: Sort the full dataset by revenue descending and show the top 5 rows for selected columns
top5_revenue = sales.sort_values(by='revenue', ascending=False)[['store', 'category', 'units_sold', 'revenue']].head(5)
top5_revenue

       store     category  units_sold  revenue
1982    Rome  ELECTRONICS        77.0  7021.63
69     Utica  electronics        78.0  6814.08
3334  Albany  Electronics        66.0  6395.40
3013  Albany  electronics        76.0  6259.36
1241   Utica  Electronics        70.0  6120.10

**3b.** Sort the dataset by `store` (ascending) and then `units_sold` (descending) within each store. Print the first 10 rows of the result, showing only `store` and `units_sold`.

In [14]:
# TODO 3b
# 3b: Sort by two columns at once with different sort directions (store ascending, revenue descending)
sorted_multi = sales.sort_values(by=['store', 'revenue'], ascending=[True, False])
sorted_multi.head()

            date   store     category  units_sold  revenue
3334  2025-05-18  Albany  Electronics        66.0  6395.40
3013  2025-04-05  Albany  electronics        76.0  6259.36
1467  2025-07-19  Albany  Electronics        78.0  6119.88
3740  2025-03-15  Albany  electronics        71.0  6049.20
532   2025-10-12  Albany  electronics        66.0  5866.08

---
## Part 4 — Group & Aggregate (30%)

**4a.** Compute total revenue per store. Which store has the highest total?

In [15]:
# TODO 4a
# 4a: Compute total revenue per store and identify the store with the highest revenue
store_revenue = sales.groupby('store')['revenue'].sum()
top_store = store_revenue.idxmax()

print("Total Revenue per Store:\n", store_revenue)
print("\nHighest Revenue Store:", top_store)

Total Revenue per Store:
 store
Albany      1478141.38
Rome        1513342.88
Syracuse    1503175.92
Utica       1557200.64
Name: revenue, dtype: float64

Highest Revenue Store: Utica

**4b.** Compute the average `units_sold` per category (using the raw, uncleaned category column — yes, this means you'll get more than 5 groups, and that's expected for this assignment).

In [16]:
# TODO 4b
# 4b: Compute the average units sold per category
avg_units_per_category = sales.groupby('category')['units_sold'].mean()
avg_units_per_category

category
Cloth ing       64.338403
Clothing        63.767068
ELECTRONICS     44.167401
Electronics     42.838828
Groceries      130.081206
Home Goods      37.578947
Home_Goods      36.199262
Toys            25.901596
clothing        65.596610
electronics     44.384030
groceries      129.967089
home goods      38.818182
toys            26.068966
Name: units_sold, dtype: float64

**4c.** Using `.agg()`, compute both the **sum** and the **count** of `revenue` per store in a single call. Then sort the result so the store with the highest total revenue appears first.

In [ ]:
# TODO 4c
# 4c: Compute sum and count of revenue per store using .agg(), then sort by total revenue descending
store_revenue_stats = sales.groupby('store')['revenue'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)
store_revenue_stats

                 sum  count
store
Utica     1557200.64   1014
Rome      1513342.88   1013
Syracuse  1503175.92    962
Albany    1478141.38    990

**4d.** Group by **both** `store` and `category` together, and compute total revenue for each store/category combination. Print just the first 10 rows of the result.

In [ ]:
# TODO 4d
# 4d: Group by two columns together ('store' and 'category') and calculate total revenue
store_category_revenue = sales.groupby(['store', 'category'])['revenue'].sum()
store_category_revenue

store     category
Albany    Cloth ing       98004.81
          Clothing       100251.59
          ELECTRONICS    191417.17
          Electronics    271509.46
          Groceries       89196.62
          Home Goods      67798.81
          Home_Goods      69472.98
          Toys            36018.32
          clothing       114890.85
          electronics    207733.37
          groceries       76079.78
          home goods     116283.31
          toys            39484.31
Rome      Cloth ing      101963.25
          Clothing       108506.69
          ELECTRONICS    225963.96
          Electronics    228396.23
          Groceries       94041.70
          Home Goods      86804.75
          Home_Goods      96541.50
          Toys            38747.76
          clothing       125512.98
          electronics    225675.50
          groceries       82925.27
          home goods      56926.25
          toys            41337.04
Syracuse  Cloth ing       87605.12
          Clothing       106943.41
          ELECTRONICS    242168.06
          Electronics    198506.16
          Groceries       87860.34
          Home Goods      80314.05
          Home_Goods      73797.41
          Toys            33235.80
          clothing       106806.55
          electronics    297012.38
          groceries       75928.55
          home goods      72632.74
          toys            40365.35
Utica     Cloth ing      121940.98
          Clothing        64543.80
          ELECTRONICS    210892.57
          Electronics    277553.27
          Groceries       93230.39
          Home Goods      81765.31
          Home_Goods      75549.53
          Toys            38261.65
          clothing       114551.59
          electronics    259968.97
          groceries      101803.71
          home goods      79343.09
          toys            37795.78
Name: revenue, dtype: float64

---
## Part 5 — Written Reflection (10%)

Answer in 2–4 sentences total, in this markdown cell (double-click to edit):

**Question:** Based on what you found in Part 4, if the retail chain wanted to trust the "average units sold per category" numbers you calculated in 4b for a real business decision, what would you tell them about whether those numbers are reliable right now? What specifically would need to happen before you'd trust them?

The current "average units sold per category" numbers are not reliable enough for real business decisions due to uncleaned data quality issues. Inconsistent category formatting (such as mixing "Electronics" and "electronics") splits identical product lines into separate groups, while missing values distort the actual aggregate calculations. Before these numbers can be trusted, the dataset needs a comprehensive data cleaning process to standardize text casing, remove trailing whitespace, and properly handle missing values.

---
### AI Use Disclosure

*If you used an AI tool (Claude, ChatGPT, GitHub Copilot, etc.) for any part of this assignment, briefly state where and how below, and how you verified the result. If you did not use any AI tool, write "No AI tools were used."*

I used an AI assistant (Gemini) to verify the correct pandas syntax and debug code execution errors after writing my initial code. I relied on it to check column name references, structure groupby aggregation methods properly, and assist in phrasing the written reflection. I verified all generated code by executing every cell sequentially in my Jupyter environment and confirming that the outputs matched the requested assignment instructions.